#!/usr/bin/env bash
# a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.

# update server and install haproxy
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  ron116-frontend
        bind *:80
        mode http
        default_backend ron116-backend
backend ron116-backend
        balance roundrobin
        server 265025-web-01 34.232.68.7:80 check
        server 265025-web-02 3.94.213.215:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
