#!/usr/bin/env bash
# Bash script that uses ssh to connect to your server using
# the private key ~/.ssh/school with the user ubuntu
# Only use ssh single-character flags
# You cannot use -l
# You do not need to handle the case of a private key protected by a passphrase

ssh ubuntu@52.87.233.177 -i ~/.ssh/school
